apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: testproject
  namespace: argocd
spec:
  namespaceResourceBlacklist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'