name: Show GitHub Event Payload

on:
  workflow_dispatch:

jobs:
  dump-event:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub event context
        run: |
          echo "Full event payload:"
          cat $GITHUB_EVENT_PATH


